apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: a9s-challenge-controller-manager-binding
subjects:
- kind: ServiceAccount
  name: a9s-challenge-controller-manager
  namespace: a9s-challenge-system
roleRef:
  kind: ClusterRole
  name: manager-role
  apiGroup: rbac.authorization.k8s.io
